=== GSA-TTS/FAC/backend/schemas/output/sections/GeneralInformation.schema.json
{
   "$id": "http://example.org/generalinformation",
   "$schema": "https://json-schema.org/draft/2019-09/schema#",
   "additionalProperties": false,
   "metamodel_version": "1.7.0",
   "properties": {
      "audit_period_covered": {
         "description": "Period type of audit being submitted",
         "enum": [
            "annual",
            "biennial",
            "other"
         ],
         "title": "AuditPeriod",
         "type": "string"
      },
      "audit_period_other_months": {
         "maxLength": 2,
         "minLength": 0,
         "pattern": "^0?[1-9]$|^1[0-8]$",
         "type": "string"
      },
      "audit_type": {
         "oneOf": [
            {
               "description": "Type of audit being submitted",
               "enum": [
                  "program-specific",
                  "single-audit"
               ],
               "title": "AuditType",
               "type": "string"
            },
            {
               "const": "GSA_MIGRATION",
               "type": "string"
            }
         ]
      },
      "auditee_address_line_1": {
         "maxLength": 100,
         "minLength": 2,
         "type": "string"
      },
      "auditee_city": {
         "maxLength": 100,
         "minLength": 2,
         "type": "string"
      },
      "auditee_contact_name": {
         "maxLength": 100,
         "minLength": 2,
         "type": "string"
      },
      "auditee_contact_title": {
         "maxLength": 100,
         "minLength": 2,
         "type": "string"
      },
      "auditee_email": {
         "oneOf": [
            {
               "format": "email",
               "maxLength": 320,
               "minLength": 6,
               "type": "string"
            },
            {
               "const": "GSA_MIGRATION",
               "type": "string"
            }
         ],
         "type": "string"
      },
      "auditee_fiscal_period_end": {
         "format": "date"
      },
      "auditee_fiscal_period_start": {
         "format": "date"
      },
      "auditee_name": {
         "maxLength": 100,
         "minLength": 5,
         "type": "string"
      },
      "auditee_phone": {
         "pattern": "^^(\\+0?1\\s)?\\(?\\d{3}\\)?[\\s.-]?\\d{3}[\\s.-]?\\d{4}$",
         "type": "string"
      },
      "auditee_state": {
         "description": "US States 2-letter abbreviations",
         "enum": [
            "AK",
            "AL",
            "AR",
            "AS",
            "AZ",
            "CA",
            "CO",
            "CT",
            "DC",
            "DE",
            "FL",
            "FM",
            "GA",
            "GU",
            "HI",
            "IA",
            "ID",
            "IL",
            "IN",
            "KS",
            "KY",
            "LA",
            "MA",
            "MD",
            "ME",
            "MH",
            "MI",
            "MN",
            "MO",
            "MP",
            "MS",
            "MT",
            "NC",
            "ND",
            "NE",
            "NH",
            "NJ",
            "NM",
            "NV",
            "NY",
            "OH",
            "OK",
            "OR",
            "PA",
            "PR",
            "PW",
            "RI",
            "SC",
            "SD",
            "TN",
            "TX",
            "UT",
            "VA",
            "VI",
            "VT",
            "WA",
            "WI",
            "WV",
            "WY"
         ]
      },
      "auditee_uei": {
         "oneOf": [
            {
               "allOf": [
                  {
                     "maxLength": 12,
                     "minLength": 12
                  },
                  {
                     "pattern": "^[A-HJ-NP-Z1-9][A-HJ-NP-Z0-9]+$"
                  },
                  {
                     "pattern": "^(?![A-HJ-NP-Z1-9]+[A-HJ-NP-Z0-9]*?[0-9]{9})[A-HJ-NP-Z0-9]*$"
                  },
                  {
                     "pattern": "^(?![0-9]{9})"
                  }
               ],
               "type": "string"
            },
            {
               "const": "GSA_MIGRATION",
               "type": "string"
            }
         ]
      },
      "auditee_zip": {
         "oneOf": [
            {
               "pattern": "^[0-9]{5}(?:[0-9]{4})?$",
               "type": "string"
            },
            {
               "const": "GSA_MIGRATION",
               "type": "string"
            }
         ]
      },
      "auditor_address_line_1": {
         "maxLength": 100,
         "minLength": 0,
         "type": "string"
      },
      "auditor_city": {
         "maxLength": 100,
         "minLength": 0,
         "type": "string"
      },
      "auditor_contact_name": {
         "maxLength": 100,
         "minLength": 2,
         "type": "string"
      },
      "auditor_contact_title": {
         "maxLength": 100,
         "minLength": 2,
         "type": "string"
      },
      "auditor_country": {
         "description": "USA or International",
         "enum": [
            "USA",
            "non-USA"
         ],
         "title": "CountryType",
         "type": "string"
      },
      "auditor_ein": {
         "oneOf": [
            {
               "pattern": "^[0-9]{9}$",
               "type": "string"
            },
            {
               "const": "GSA_MIGRATION",
               "type": "string"
            }
         ]
      },
      "auditor_ein_not_an_ssn_attestation": {
         "type": "boolean"
      },
      "auditor_email": {
         "oneOf": [
            {
               "format": "email",
               "maxLength": 320,
               "minLength": 6,
               "type": "string"
            },
            {
               "const": "GSA_MIGRATION",
               "type": "string"
            }
         ]
      },
      "auditor_firm_name": {
         "maxLength": 100,
         "minLength": 5,
         "type": "string"
      },
      "auditor_international_address": {
         "maxLength": 100,
         "minLength": 0,
         "type": "string"
      },
      "auditor_phone": {
         "pattern": "^^(\\+0?1\\s)?\\(?\\d{3}\\)?[\\s.-]?\\d{3}[\\s.-]?\\d{4}$",
         "type": "string"
      },
      "auditor_state": {
         "description": "US States 2-letter abbreviations",
         "enum": [
            "AK",
            "AL",
            "AR",
            "AS",
            "AZ",
            "CA",
            "CO",
            "CT",
            "DC",
            "DE",
            "FL",
            "FM",
            "GA",
            "GU",
            "HI",
            "IA",
            "ID",
            "IL",
            "IN",
            "KS",
            "KY",
            "LA",
            "MA",
            "MD",
            "ME",
            "MH",
            "MI",
            "MN",
            "MO",
            "MP",
            "MS",
            "MT",
            "NC",
            "ND",
            "NE",
            "NH",
            "NJ",
            "NM",
            "NV",
            "NY",
            "OH",
            "OK",
            "OR",
            "PA",
            "PR",
            "PW",
            "RI",
            "SC",
            "SD",
            "TN",
            "TX",
            "UT",
            "VA",
            "VI",
            "VT",
            "WA",
            "WI",
            "WV",
            "WY"
         ]
      },
      "auditor_zip": {
         "oneOf": [
            {
               "pattern": "^[0-9]{5}(?:[0-9]{4})?$",
               "type": "string"
            },
            {
               "const": "GSA_MIGRATION",
               "type": "string"
            }
         ]
      },
      "ein": {
         "oneOf": [
            {
               "pattern": "^[0-9]{9}$",
               "type": "string"
            },
            {
               "const": "GSA_MIGRATION",
               "type": "string"
            }
         ]
      },
      "ein_not_an_ssn_attestation": {
         "type": "boolean"
      },
      "is_usa_based": {
         "type": "boolean"
      },
      "met_spending_threshold": {
         "type": "boolean"
      },
      "multiple_eins_covered": {
         "type": "boolean"
      },
      "multiple_ueis_covered": {
         "type": "boolean"
      },
      "secondary_auditors_exist": {
         "type": "boolean"
      },
      "user_provided_organization_type": {
         "description": "Org type",
         "enum": [
            "state",
            "local",
            "tribal",
            "higher-ed",
            "non-profit",
            "unknown",
            "none"
         ],
         "title": "OrganizationType",
         "type": "string"
      }
   },
   "title": "GeneralInformation",
   "type": "object",
   "version": null
}

=== GSA-TTS/FAC/backend/audit/fixtures/json/general-information--test0001test--simple-pass.json
{
  "ein": "123456789",
  "audit_type": "single-audit",
  "auditee_uei": "TEST0001TEST",
  "auditee_zip": "94109",
  "auditor_ein": "987654321",
  "auditor_zip": "94109",
  "auditee_city": "HAL",
  "auditee_name": "IBM Corporation",
  "auditor_city": "Rivendell",
  "is_usa_based": true,
  "auditee_email": "fictional.fac.tester+test@gsa.gov",
  "auditee_phone": "5558675309",
  "auditee_state": "CA",
  "auditor_email": "fictional.fac.tester+test@gsa.gov",
  "auditor_phone": "5558675309",
  "auditor_state": "CA",
  "auditor_country": "USA",
  "auditor_firm_name": "Fellowship",
  "audit_period_covered": "annual",
  "auditee_contact_name": "Frodo Baggins",
  "auditor_contact_name": "Sauron",
  "auditee_contact_title": "Ringbearer",
  "auditor_contact_title": "Dark Lord",
  "multiple_eins_covered": false,
  "multiple_ueis_covered": false,
  "auditee_address_line_1": "HAL",
  "auditor_address_line_1": "Main Hall",
  "met_spending_threshold": true,
  "secondary_auditors_exist": false,
  "audit_period_other_months": "",
  "auditee_fiscal_period_end": "2023-01-01",
  "ein_not_an_ssn_attestation": true,
  "auditee_fiscal_period_start": "2022-01-01",
  "user_provided_organization_type": "non-profit",
  "auditor_ein_not_an_ssn_attestation": true 
}
